/**
 * A namespace for enumerations.
 *
 * @namespace Enums
 */

/**
 * A meta namespace for signatures of anonymous functions.
 *
 * @namespace Callbacks
 */

/**
 * The signature of a function which accepts events generated by a
 * MarketDepth subscription (see {@link Enums.SubscriptionType}).
 *
 * @public
 * @callback MarketDepthCallback
 * @memberOf Callbacks
 * @param {Schema.Book} book
 */

/**
 * The signature of a function which accepts events generated by a
 * MarketUpdate subscription (see {@link Enums.SubscriptionType}).
 *
 * @public
 * @callback MarketUpdateCallback
 * @memberOf Callbacks
 * @param {Object} data
 */

/**
 * The signature of a function which accepts events generated by a
 * CumulativeVolume subscription (see {@link Enums.SubscriptionType}).
 *
 * @public
 * @callback CumulativeVolumeCallback
 * @memberOf Callbacks
 * @param {Object} data
 */

/**
 * The signature of a function which accepts events generated by a
 * Timestamp subscription (see {@link Enums.SubscriptionType}).
 *
 * @public
 * @callback TimestampCallback
 * @memberOf Callbacks
 * @param {Date} date
 */

/**
 * The signature of a function which accepts events generated by an
 * Events subscription (see {@link Enums.SubscriptionType}).
 *
 * @public
 * @callback EventsCallback
 * @memberOf Callbacks
 * @param {Enums.ConnectionEventType} data
 */